name: cvnav
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - black==25.9.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cycler==0.12.1
      - filelock==3.20.0
      - flake8==7.3.0
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - idna==3.11
      - iniconfig==2.3.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lightning-utilities==0.15.2
      - lpips==0.1.4
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mccabe==0.7.0
      - mpmath==1.3.0
      - mypy-extensions==1.1.0
      - networkx==3.4.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pathspec==0.12.1
      - pillow==12.0.0
      - platformdirs==4.5.0
      - pluggy==1.6.0
      - protobuf==6.33.0
      - pycodestyle==2.14.0
      - pyflakes==3.4.0
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pytest==8.4.2
      - pytokens==0.3.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - scikit-learn==1.7.2
      - sentry-sdk==2.43.0
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tomli==2.3.0
      - torch==2.9.0
      - torchaudio==2.9.0
      - torchmetrics==1.8.2
      - torchvision==0.24.0
      - triton==3.5.0
      - urllib3==2.5.0
      - wandb==0.22.3
